# Generated by Django 4.1.4 on 2022-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_priority',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
